name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.SSH_HOST }} $(ssh-keyscan -t ed25519 ${{ secrets.SSH_HOST }} 2>/dev/null)" >> ~/.ssh/known_hosts

      - name: Test Connection
        run: |
          echo "Testing direct connection..."
          nc -zv ${{ secrets.SSH_HOST }} 22 || true
          echo "Testing SSH connection..."
          ssh -v -i ~/.ssh/deploy_key root@${{ secrets.SSH_HOST }} 'echo "Connected successfully"'

      - name: Deploy
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key root@${{ secrets.SSH_HOST }} '
            cd /root/cladbe_server &&
            git pull origin main &&
            npm install &&
            pm2 restart all
          '
