name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_HOST }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/deploy_key

      - name: Deploy to Server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" \
            --exclude '.git*' \
            --exclude 'node_modules' \
            --delete ./ root@${{ secrets.SSH_HOST }}:/root/my-api/
          ssh -i ~/.ssh/deploy_key root@${{ secrets.SSH_HOST }} 'cd /root/my-api && npm install && pm2 restart all'
