name: Deploy to Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 194.164.149.231 >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          # Convert each key-value pair to env format but keep FIREBASE_CONFIG as JSON
          env_file_content=$(echo "$ENV_VARS" | sed 's/{//' | sed 's/}//' | tr ',' '\n' | sed 's/^[[:space:]]*//' | \
          awk -F': ' '{
            if ($1 ~ /FIREBASE_CONFIG/) {
              print $1"="$2
              next
            }
            gsub(/\"/, "", $1)
            gsub(/\"/, "", $2)
            print $1"="$2
          }')
          ssh -i ~/.ssh/github_deploy root@194.164.149.231 "cd /root/cladbe_server && \
          echo \"$env_file_content\" > .env && \
          git pull origin main && \
          npm install && \
          pm2 restart ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production"
