name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/github_deploy root@80.65.208.176 'bash -s' << 'ENDSSH'
            cd /root/cladbe_server
            
            echo "Pulling latest changes..."
            git pull origin main
            
            echo "Installing dependencies..."
            npm install --production
            
            echo "Stopping PM2..."
            pm2 kill || true
            rm -rf ~/.pm2
            
            echo "Starting PM2 with all instances..."
            pm2 start ecosystem.config.js --env production
            
            echo "Waiting for instances to start..."
            sleep 10
            
            echo "Final process status:"
            pm2 list
            
            # Check if all instances are online
            ONLINE_COUNT=$(pm2 list | grep "online" | wc -l)
            if [ "$ONLINE_COUNT" -eq 4 ]; then
              echo "All instances are running successfully"
              pm2 save
              exit 0
            else
              echo "Not all instances are online (running: $ONLINE_COUNT)"
              exit 1
            fi
          ENDSSH
