name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

      - name: Copy ENV file
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          echo "$ENV_VARS" > .env
          scp -i ~/.ssh/github_deploy .env root@80.65.208.176:/root/cladbe_server/.env

      - name: Deploy
        run: |
          ssh -i ~/.ssh/github_deploy root@80.65.208.176 'bash -s' << 'ENDSSH'
            cd /root/cladbe_server
            
            echo "Pulling latest changes..."
            git pull origin main
            
            echo "Installing dependencies..."
            npm install --production
            
            echo "Stopping PM2..."
            pm2 kill || true
            rm -rf ~/.pm2
            
            echo "Starting PM2..."
            pm2 start ecosystem.config.js --env production
            
            # Give more time for instances to start
            echo "Waiting for instances to start..."
            sleep 15
            
            # Check if all instances are online
            ONLINE_COUNT=$(pm2 list | grep "online" | wc -l)
            if [ "$ONLINE_COUNT" -eq 4 ]; then
              echo "All instances are online"
              pm2 save
              pm2 list
              exit 0
            else
              echo "Not all instances are online. Current status:"
              pm2 list
              exit 1
            fi
          ENDSSH
