name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/github_deploy root@80.65.208.176 'bash -s' << 'ENDSSH'
            cd /root/cladbe_server

            echo "Stashing changes except .env..."
            git stash -- :/

            echo "Pulling latest changes..."
            git pull origin main

            echo "Installing dependencies..."
            npm install --production

            echo "Stopping PM2..."
            pm2 kill || true
            rm -rf ~/.pm2
            pm2 update

            echo "Starting PM2 with all instances..."
            pm2 start ecosystem.config.js --env production

            # Wait for instances to start with a timeout
            echo "Waiting for instances to start..."
            TIMEOUT=60
            START_TIME=$(date +%s)
            
            while true; do
              CURRENT_TIME=$(date +%s)
              ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
              
              if [ $ELAPSED_TIME -gt $TIMEOUT ]; then
                echo "Timeout waiting for instances"
                exit 1
              fi
              
              ONLINE_COUNT=$(pm2 list | grep "online" | wc -l)
              echo "Currently $ONLINE_COUNT instances online..."
              
              if [ "$ONLINE_COUNT" -eq 13 ]; then
                echo "All instances are running successfully"
                pm2 save
                exit 0
              fi
              
              sleep 5
            done
          ENDSSH