name: Deploy to Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

          # Start ssh-agent and add key with passphrase
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | SSH_ASKPASS_REQUIRE=never ssh-add ~/.ssh/github_deploy

          # Test the connection
          ssh -o StrictHostKeyChecking=no root@80.65.208.176 'echo "SSH connection successful"'

      - name: Deploy
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          # Restart ssh-agent and add key again for this step
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | SSH_ASKPASS_REQUIRE=never ssh-add ~/.ssh/github_deploy

          echo "$ENV_VARS" > .env.tmp

          ssh -o StrictHostKeyChecking=no root@80.65.208.176 'cd /root/cladbe_server && \
          git pull origin main && \
          npm install && \
          pm2 stop ecosystem.config.js || true && \
          pm2 delete ecosystem.config.js || true && \
          pm2 flush && \
          pm2 start ecosystem.config.js --env production --no-autorestart'
