name: Deploy to Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          # Debug: Check if SSH_PRIVATE_KEY is set
          echo "SSH key length: $(echo "$SSH_PRIVATE_KEY" | wc -c)"

          # Write the key with explicit EOF markers
          cat << 'EOF' > ~/.ssh/github_deploy
          $SSH_PRIVATE_KEY
          EOF

          chmod 600 ~/.ssh/github_deploy

          # Debug: Verify key file exists and content
          echo "=== Key File Info ==="
          ls -la ~/.ssh/github_deploy
          echo "Key file size: $(wc -c < ~/.ssh/github_deploy)"

          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

          # Debug: Print key info
          echo "=== Key Info ==="
          ssh-keygen -l -f ~/.ssh/github_deploy || echo "Failed to read key"

          # Start ssh-agent
          eval $(ssh-agent -s)

          # Add key using sshpass
          expect << 'EOD'
            spawn ssh-add ~/.ssh/github_deploy
            expect "Enter passphrase"
            send "${SSH_PASSPHRASE}\r"
            expect eof
          EOD

          # List added keys
          ssh-add -l

          # Test SSH connection with debug
          ssh -v -o StrictHostKeyChecking=no root@80.65.208.176 'echo "Test connection"'

      - name: Deploy
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          # Start ssh-agent again for this step
          eval $(ssh-agent -s)

          # Add key using expect
          expect << 'EOD'
            spawn ssh-add ~/.ssh/github_deploy
            expect "Enter passphrase"
            send "${SSH_PASSPHRASE}\r"
            expect eof
          EOD

          echo "$ENV_VARS" > .env.tmp

          ssh -o StrictHostKeyChecking=no root@80.65.208.176 'cd /root/cladbe_server && \
          git pull origin main && \
          npm install && \
          pm2 stop ecosystem.config.js || true && \
          pm2 delete ecosystem.config.js || true && \
          pm2 flush && \
          pm2 start ecosystem.config.js --env production --no-autorestart'
