name: Deploy to Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

          # Debug information
          echo "=== SSH Key Debug Info ==="
          ls -la ~/.ssh/github_deploy
          echo "=== SSH Key Type ==="
          ssh-keygen -l -f ~/.ssh/github_deploy || echo "Invalid key format"
          echo "=== Known Hosts Content ==="
          cat ~/.ssh/known_hosts
          echo "=== Testing SSH Connection ==="
          ssh -v -i ~/.ssh/github_deploy root@80.65.208.176 exit

      - name: Deploy
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          echo "$ENV_VARS" > .env.tmp

          ssh -v -i ~/.ssh/github_deploy root@80.65.208.176 'cd /root/cladbe_server && \
          git pull origin main && \
          npm install && \
          pm2 stop ecosystem.config.js || true && \
          pm2 delete ecosystem.config.js || true && \
          pm2 flush && \
          pm2 start ecosystem.config.js --env production --no-autorestart'
