name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          sudo mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          sudo mv deploy_key ~/.ssh/deploy_key
          sudo chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} | sudo tee -a ~/.ssh/known_hosts

      - name: Deploy
        run: |
          sudo ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} '
            cd /root/cladbe_server &&
            git pull origin main &&
            npm install &&
            pm2 restart all
          '
