name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test SSH Connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 194.164.149.231 >> ~/.ssh/known_hosts

      - name: Deploy
        if: success()
        run: |
          ssh -i ~/.ssh/github_deploy root@194.164.149.231 '
            cd /root/cladbe_server &&
            git pull origin main &&
            npm install &&
            if pm2 list | grep -q "cladbe"; then
              pm2 restart cladbe
            else
              pm2 start src/index.js --name cladbe
            fi
          '
