name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

      - name: Copy ENV file
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          echo "$ENV_VARS" > .env
          scp -i ~/.ssh/github_deploy .env root@80.65.208.176:/root/cladbe_server/.env

      - name: Stop Existing PM2
        run: |
          ssh -i ~/.ssh/github_deploy root@80.65.208.176 'pm2 kill || true && rm -rf ~/.pm2'

      - name: Deploy and Start
        run: |
          ssh -i ~/.ssh/github_deploy root@80.65.208.176 'bash -s' << 'ENDSSH'
            cd /root/cladbe_server
            
            echo "Pulling latest changes..."
            git pull origin main
            
            echo "Installing dependencies..."
            npm install --production
            
            echo "Starting PM2..."
            pm2 start ecosystem.config.js --env production
            
            echo "Saving PM2 configuration..."
            pm2 save
            
            echo "Current processes:"
            pm2 list
          ENDSSH

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/github_deploy root@80.65.208.176 'bash -s' << 'ENDSSH'
            if pm2 list | grep -q "online"; then
              echo "Deployment successful"
              pm2 list
            else
              echo "Deployment failed"
              exit 1
            fi
          ENDSSH
