name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 80.65.208.176 >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          echo "$ENV_VARS" > .env.tmp

          ssh -i ~/.ssh/github_deploy -o StrictHostKeyChecking=no root@80.65.208.176 'bash -s' << 'ENDSSH'
            set -e
            cd /root/cladbe_server
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies
            npm install --production
            
            # Complete PM2 cleanup
            pm2 kill || true
            rm -rf ~/.pm2
            
            # Start fresh PM2
            pm2 update
            
            # Start with 4 instances
            pm2 start ecosystem.config.js --env production
            
            # Save PM2 state
            pm2 save
            
            # Verify instances
            echo "Verifying deployment..."
            sleep 5
            pm2 list
          ENDSSH
