name: Deploy to Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          ssh -i ~/.ssh/github_deploy root@194.164.149.231 "cd /root/cladbe_server && \
          echo \"$ENV_VARS\" > .env && \
          git pull origin main && \
          npm install && \
          pm2 restart ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production"
